In [202]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [203]:
df = pd.read_csv('data.csv')

In [220]:
clean_df = df.drop(columns='Person ID', axis=1)
clean_df

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure Higher,Blood Pressure Lower,Heart Rate,Daily Steps,Sleep Disorder
0,1,27,1,6.1,6,42,6,1,126,83,77,4200,0
1,1,28,0,6.2,6,60,8,0,125,80,75,10000,0
2,1,28,0,6.2,6,60,8,0,125,80,75,10000,0
3,1,28,2,5.9,4,30,8,2,140,90,85,3000,1
4,1,28,2,5.9,4,30,8,2,140,90,85,3000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,0,59,0,8.1,9,75,3,1,140,95,68,7000,1
370,0,59,0,8.0,9,75,3,1,140,95,68,7000,1
371,0,59,0,8.1,9,75,3,1,140,95,68,7000,1
372,0,59,0,8.1,9,75,3,1,140,95,68,7000,1
373,0,59,0,8.1,9,75,3,1,140,95,68,7000,1

In [227]:
clean_df['Stress Level'].describe()

count    374.000000
mean       5.385027
std        1.774526
min        3.000000
25%        4.000000
50%        5.000000
75%        7.000000
max        8.000000
Name: Stress Level, dtype: float64

In [205]:
Categorical_Col = []
Numerical_Col = []
for col in clean_df.columns:
    if clean_df[col].dtype == 'object':
        Categorical_Col.append(col)  
    else:
        Numerical_Col.append(col)

In [206]:
LE = LabelEncoder()
for col in Categorical_Col:
    clean_df[col] = LE.fit_transform(clean_df[col])

In [207]:
X = clean_df.iloc[:,:-1]
y = clean_df['Sleep Disorder']

In [208]:
X

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure Higher,Blood Pressure Lower,Heart Rate,Daily Steps
0,1,27,1,6.1,6,42,6,1,126,83,77,4200
1,1,28,0,6.2,6,60,8,0,125,80,75,10000
2,1,28,0,6.2,6,60,8,0,125,80,75,10000
3,1,28,2,5.9,4,30,8,2,140,90,85,3000
4,1,28,2,5.9,4,30,8,2,140,90,85,3000
...,...,...,...,...,...,...,...,...,...,...,...,...
369,0,59,0,8.1,9,75,3,1,140,95,68,7000
370,0,59,0,8.0,9,75,3,1,140,95,68,7000
371,0,59,0,8.1,9,75,3,1,140,95,68,7000
372,0,59,0,8.1,9,75,3,1,140,95,68,7000
373,0,59,0,8.1,9,75,3,1,140,95,68,7000

In [209]:
y

0      0
1      0
2      0
3      1
4      1
      ..
369    1
370    1
371    1
372    1
373    1
Name: Sleep Disorder, Length: 374, dtype: int64

In [210]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [211]:
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)
y_pred_tree = decision_tree.predict(X_test)
acc_tree = accuracy_score(y_test, y_pred_tree)

In [212]:
print("Decision Tree Accuracy: ", acc_tree*100," % ")
print(classification_report(y_test, y_pred_tree))

Decision Tree Accuracy:  90.42553191489363  %
              precision    recall  f1-score   support

           0       0.96      0.98      0.97        55
           1       0.89      0.77      0.83        22
           2       0.74      0.82      0.78        17

    accuracy                           0.90        94
   macro avg       0.87      0.86      0.86        94
weighted avg       0.91      0.90      0.90        94

### model variable  = decision_tree

In [228]:
import joblib

In [229]:
joblib.dump(decision_tree,'model')

['model']

In [233]:
loaded = joblib.load('model')

In [231]:
o = [[1,27,1,6.1,6,42,6,1,126,83,77,4200],[1,28,2,5.9,4,30,8,2,140,90,85,3000]]

In [232]:
loaded.predict(o)

C:\Users\rushi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0, 1], dtype=int64)